# permissions for end users to edit ippooldetails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ippooldetail-editor-role
rules:
- apiGroups:
  - ipfixed.cmos.chinamobile.com
  resources:
  - ippooldetails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipfixed.cmos.chinamobile.com
  resources:
  - ippooldetails/status
  verbs:
  - get
